//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingSeats
    {
        public int BookingSeatID { get; set; }
        public int BookingID { get; set; }
        public int SeatID { get; set; }
        public decimal Price { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
