//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bookings()
        {
            this.BookingSeats = new HashSet<BookingSeats>();
            this.Payments = new HashSet<Payments>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int SessionID { get; set; }
        public Nullable<System.DateTime> BookingDateTime { get; set; }
        public decimal TotalPrice { get; set; }
        public int StatusID { get; set; }
        public string GuestName { get; set; }
        public string GuestPhone { get; set; }
    
        public virtual Sessions Sessions { get; set; }
        public virtual BookingStatuses BookingStatuses { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingSeats> BookingSeats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
