//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CinemaDBEntities : DbContext
    {
        public CinemaDBEntities()
            : base("name=CinemaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<BookingSeats> BookingSeats { get; set; }
        public virtual DbSet<BookingStatuses> BookingStatuses { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<MovieGenres> MovieGenres { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Seats> Seats { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<Shifts> Shifts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<vw_EmployeeShifts> vw_EmployeeShifts { get; set; }
        public virtual DbSet<vw_MovieReviews> vw_MovieReviews { get; set; }
        public virtual DbSet<vw_MovieStatistics> vw_MovieStatistics { get; set; }
        public virtual DbSet<vw_SessionsFullInfo> vw_SessionsFullInfo { get; set; }
    
        public virtual ObjectResult<AddOrUpdateReview_Result> AddOrUpdateReview(Nullable<int> userID, Nullable<int> movieID, Nullable<int> rating, string comment)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var movieIDParameter = movieID.HasValue ?
                new ObjectParameter("MovieID", movieID) :
                new ObjectParameter("MovieID", typeof(int));
    
            var ratingParameter = rating.HasValue ?
                new ObjectParameter("Rating", rating) :
                new ObjectParameter("Rating", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddOrUpdateReview_Result>("AddOrUpdateReview", userIDParameter, movieIDParameter, ratingParameter, commentParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CancelBooking(Nullable<int> bookingID, Nullable<int> userID)
        {
            var bookingIDParameter = bookingID.HasValue ?
                new ObjectParameter("BookingID", bookingID) :
                new ObjectParameter("BookingID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CancelBooking", bookingIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<CreateBooking_Result> CreateBooking(Nullable<int> userID, Nullable<int> sessionID, string guestName, string guestPhone, string seatIDs, Nullable<decimal> totalPrice)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var sessionIDParameter = sessionID.HasValue ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(int));
    
            var guestNameParameter = guestName != null ?
                new ObjectParameter("GuestName", guestName) :
                new ObjectParameter("GuestName", typeof(string));
    
            var guestPhoneParameter = guestPhone != null ?
                new ObjectParameter("GuestPhone", guestPhone) :
                new ObjectParameter("GuestPhone", typeof(string));
    
            var seatIDsParameter = seatIDs != null ?
                new ObjectParameter("SeatIDs", seatIDs) :
                new ObjectParameter("SeatIDs", typeof(string));
    
            var totalPriceParameter = totalPrice.HasValue ?
                new ObjectParameter("TotalPrice", totalPrice) :
                new ObjectParameter("TotalPrice", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreateBooking_Result>("CreateBooking", userIDParameter, sessionIDParameter, guestNameParameter, guestPhoneParameter, seatIDsParameter, totalPriceParameter);
        }
    
        public virtual ObjectResult<GetAvailableSeats_Result> GetAvailableSeats(Nullable<int> sessionID)
        {
            var sessionIDParameter = sessionID.HasValue ?
                new ObjectParameter("SessionID", sessionID) :
                new ObjectParameter("SessionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAvailableSeats_Result>("GetAvailableSeats", sessionIDParameter);
        }
    
        public virtual ObjectResult<GetSessionsByDate_Result> GetSessionsByDate(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSessionsByDate_Result>("GetSessionsByDate", dateParameter);
        }
    
        public virtual ObjectResult<GetUserBookings_Result> GetUserBookings(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserBookings_Result>("GetUserBookings", userIDParameter);
        }
    }
}
