//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seats()
        {
            this.BookingSeats = new HashSet<BookingSeats>();
        }
    
        public int SeatID { get; set; }
        public int HallID { get; set; }
        public int RowNumber { get; set; }
        public int SeatNumber { get; set; }
        public string Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingSeats> BookingSeats { get; set; }
        public virtual Halls Halls { get; set; }
    }
}
