//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MovieStatistics
    {
        public int MovieID { get; set; }
        public string Title { get; set; }
        public Nullable<int> TotalSessions { get; set; }
        public Nullable<int> TotalBookings { get; set; }
        public decimal TotalRevenue { get; set; }
        public int AverageRating { get; set; }
        public Nullable<int> ReviewCount { get; set; }
    }
}
