//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SessionsFullInfo
    {
        public int SessionID { get; set; }
        public string MovieTitle { get; set; }
        public string MovieDescription { get; set; }
        public int Duration { get; set; }
        public string AgeRestriction { get; set; }
        public string HallName { get; set; }
        public int HallCapacity { get; set; }
        public System.DateTime SessionDateTime { get; set; }
        public decimal BasePrice { get; set; }
        public Nullable<int> AvailableSeats { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
